---
resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

  - name: slack-alert
    type: registry-image
    source:
      repository: arbourd/concourse-slack-alert-resource

resources:
  - name: git-master
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-shielded-vulnerable-people-service
      branch: task/deployment-to-concourse

#  - name: slack
#    type: slack-alert
#    source:
#      url: ((slack_hook_automate))
#      channel: covid-engineering-team
#
## Anchors for later
#slack_alert_on_failure: &slack_alert_on_failure
#  put: slack
#  params:
#    alert_type: failed
#
#slack_alert_on_success: &slack_alert_on_success
#  put: slack
#  params:
#    alert_type: success

jobs:
  - name: update-pipeline
    serial: true
    plan:
      - get: git-master
        trigger: true
      - set_pipeline: svp-form
        file: git-master/concourse/pipeline.yml
#    on_failure: *slack_alert_on_failure

  - name: test
    serial: true
    plan:
    - get: git-master
      trigger: true
      passed: [update-pipeline]
    - task: test
      file: git-master/concourse/tasks/test.yml
#    on_failure: *slack_alert_on_failure

  - name: deploy-to-staging
    serial: true
    plan:
      - get: git-master
        trigger: true
        passed: [test]
      - task: deploy-to-paas
        config:
        file: git-master/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          CF_SPACE: staging
          INSTANCES: 5
          CF_STARTUP_TIMEOUT: 5 # minutes
          HOSTNAME: gds-shielded-vulnerable-people-service-staging
          GOVUK_NOTIFY_EMAIL_TEMPLATE_ID: d4fddfce-1dfd-4ff5-ab42-156e6ba3e76b
          GOVUK_NOTIFY_SMS_TEMPLATE_ID: a2166a39-91f5-4370-bbbf-c59276975d49
          NOTIFY_API_KEY: ((svp-form/notify-api-key-stg))
          SECRET_KEY: ((svp-form/flask-secret-key-base-stg))
          NHS_OIDC_AUTHORITY_URL: https://auth.aos.signin.nhs.uk
          NHS_OIDC_LOGIN_CALLBACK_URL: https://gds-shielded-vulnerable-people-service-staging.london.cloudapps.digital/nhs-login-callback
          NHS_OIDC_REGISTRATION_CALLBACK_URL: https://gds-shielded-vulnerable-people-service-staging.london.cloudapps.digital/nhs-registration-callback
          AWS_ACCESS_KEY: ((svp-form/aws-access-key-id-stg))
          AWS_SECRET_ACCESS_KEY: ((svp-form/aws-secret-access-key-stg))
          NHS_OIDC_LOGIN_PRIVATE_KEY: ((svp-form/nhs-login-private-key-stg))
#        on_failure: *slack_alert_on_failure

  - name: smoke-test-staging
    plan:
      - get: git-master
        trigger: true
        passed: [deploy-to-staging]
      - task: smoke-test
        file: git-master/concourse/tasks/smoke-test.yml
        params:
          URL: 'https://gds-shielded-vulnerable-people-service-staging.london.cloudapps.digital/live-in-england'
          MESSAGE: "Checks that the application deployed to staging is not serving HTTP error codes"
#        on_failure: *slack_alert_on_failure

  - name: e2e-test-staging
    serial: true
    plan:
    - get: git-master
      trigger: true
      passed: [smoke-test-staging]
    - task: e2e-test
      file: git-master/concourse/tasks/e2e-test.yml
      attempts: 2
      params:
        CF_SPACE: "staging"
        ENVIRONMENT: "staging"
        URL: "https://gds-shielded-vulnerable-people-service-staging.london.cloudapps.digital"
        MESSAGE: "Checks that the application deployed to staging is not serving HTTP error codes"
#      on_failure: *slack_alert_on_failure