platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/curl-ssl
run:
  path: sh
  args:
    - -c
    - |
      set -ue
      echo 'Curling cronitor'
      curl --fail "$CRONITOR_URL/complete"
      echo 'Curled cronitor successfully'
