platform: linux
image_resource:
  type: registry-image
  source:
    repository: gdscyber/concourse-chrome-driver
    tag: latest
params:
  CGO_ENABLE: "0"
  DEBIAN_FRONTEND: "noninteractive"
  PYTHONIOENCODING: "UTF-8"
inputs:
- name: git-master
outputs:
- name: builds
run:
  path: /bin/bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      echo "running smoke tests against \"${WEB_APP_BASE_URL}\""
      make smoke_test ENV="${ENVIRONMENT}"
  dir: git-master
