---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: python
    tag: 3.8.5-slim-buster
params:
  DEBIAN_FRONTEND: "noninteractive"
inputs:
- name: git-master
run:
  path: /bin/bash
  args:
    - -euo
    - pipefail
    - -c
    - |
      root=$(pwd)
      make install
      echo "Executing unit tests..."
      make test_with_coverage
  dir: git-master
